default_platform :ios

platform :ios do

  app_store_connect_api_key(
    key_id: "6799V93787",
    issuer_id: "aaa4f5f7-4cac-4ceb-b1cb-1576e7e8519f",
    key_filepath: ENV["FASTLANE_KEY_FILEPATH"],
    duration: 1200,
    in_house: false
  )

  lane :build do
    match(
      type: "appstore",
      readonly: false
    )
    build_app(scheme: "JoinSelf Demo")
  end

  lane :publish do
    upload_to_testflight(
      ipa: "build-artifacts/demo-ios/ExampleApp.ipa",
      skip_waiting_for_build_processing: true
    )
  end

end
