name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

defaults:
  run:
    shell: bash

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: joinself/actions-public/setup-job@main
      - uses: actions/checkout@v6
      - name: CI
        env:
          GH_TOKEN: ${{ secrets.GH_PAT_DEMO_IOS_GHA }}
          WORKFLOW_ID: ${{ github.run_id }}${{github.run_attempt}}
        run: |
          echo "Calling remote workflow: joinself/demo-ios-gha - CI (${WORKFLOW_ID})"
          gh workflow run CI -R joinself/demo-ios-gha -r main -f id=${WORKFLOW_ID} -f git-ref=${GITHUB_REF_NAME}
          ${SCRIPTS}/workflow-wait joinself/demo-ios-gha ${WORKFLOW_ID}
